In [1]:
import numpy as np 



In [2]:
a = np.arange(24).reshape(4,6)



In [3]:
print(a)





[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [4]:
#column array
print(np.c_[1,0,4])



[[1 0 4]]


In [5]:
print(np.reshape(a,(6,4)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [6]:
print(np.transpose(a))

[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [7]:
#get the max of each column
print(a.max(axis=0))

[18 19 20 21 22 23]


In [8]:
#get the max of each row
print(a.max(axis=1))

[ 5 11 17 23]


In [9]:
#get the sum of each row
print(a.sum(axis=1))

[ 15  51  87 123]


In [13]:
print(a[::+1])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
