In [14]:
import numpy as np
myarray=np.array([4,3,2])
myarray
mybigarray = np.array([[3,2,4], [3,3,2]])
mybigarray

array([[3, 2, 4],
       [3, 3, 2]])

In [15]:
myarray = np.arange(3,17,2)
myarray

array([ 3,  5,  7,  9, 11, 13, 15])

In [21]:
myarray = np.arange(3,17,2, dtype =float)
myarray

array([ 3.,  5.,  7.,  9., 11., 13., 15.])

In [22]:
myarray = np.eye(5)
myarray

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
myarray = np.zeros(7, dtype=int)
myarray

array([0, 0, 0, 0, 0, 0, 0])

In [37]:
myarray =np.ones(24, dtype = int)
myarray


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [46]:
#myarray= np.reshape(4,6)
m1 = np.arange(24).reshape(4,6)
m2 = np.arange(24).reshape(6,4)



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [47]:
m1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [48]:
m2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])