In [1]:
import numpy as np

In [16]:
a=(np.random.rand(6)*10).astype(int)
a=a.reshape(2,3)
print('array a=')
print(a)

array a=
[[4 6 9]
 [2 3 2]]


In [17]:
b=(np.random.rand(6)*10).astype(int)
b=b.reshape(3,2)
print('array b=')
print(b)

array b=
[[4 6]
 [3 5]
 [4 4]]


In [18]:
##dot product 
dotproduct = np.dot(a,b)
print(dotproduct)

[[70 90]
 [25 35]]


In [5]:
#add matrixes
#dimensions need to be the same
print(a+b)

[[11 12]
 [ 3  8]
 [10 11]]


In [6]:
#multiples values 
print(a*b)

[[30 36]
 [ 0 15]
 [24 18]]


In [23]:
## dot product
#[[1 2 3]
#[4 5 6]]
#
#[[6 3]
# [5 2]
# [4 1]]
#
#[[28 10]
# [73 28]]

a = np.arange(1,7).reshape(2,3)
print(a)
b= np.arange(1,7)[::-1].reshape(2,3)
b = np.transpose(b)
print(b)

[[1 2 3]
 [4 5 6]]
[[6 3]
 [5 2]
 [4 1]]


In [24]:
print(np.dot(a,b))

[[28 10]
 [73 28]]


In [ ]:
#Cross Product

In [ ]:
# a = (1,2,3)   b = (4,5,6)
#      i j k
#      x y z 

#        | i j k |    ignore i        ignore j     ignore k
# a X b =| 1 2 3 | = i(2x6 - 3x5) -j(1x6 - 4x3) +k(1x5 - 2x4)
#        | 4 5 6 |
#                  = i (-3) -j(-6) + k(-3)
#                  = (-3,6,-3)

In [27]:
#a=[1,2,3]
#b=[4,5,6]
a = np.arange(1,4)
b = np.arange(4,7)
print(np.cross(a,b))

[-3  6 -3]


In [35]:
#normal distribution
a= np.random.normal(0,1,100)
print(a)

[-2.51760136e-01  5.02916651e-01 -1.89516615e-02 -5.02315270e-01
  1.49498909e+00 -1.46437833e+00 -1.82535539e+00  1.73610365e+00
 -2.66638259e-01 -8.31995212e-01 -6.02917755e-01 -5.42826185e-01
 -1.78677352e+00 -1.64840427e-02  3.36227777e-01 -1.49610380e+00
  9.68871064e-01  4.29609827e-01 -2.21029845e-01 -8.58296067e-01
 -7.43037895e-01 -1.38045953e-01  1.58170613e+00 -7.64048119e-01
 -6.00982609e-01 -4.42952620e-01 -5.96118713e-01 -8.55152653e-01
 -8.92679995e-01  2.25496704e+00  2.13104386e+00 -4.97437045e-01
  7.32383208e-01  5.61190571e-01 -1.08674453e+00  9.29617627e-01
 -2.15822547e+00 -5.98460544e-01 -3.60662597e-01 -1.55290889e+00
 -5.05837486e-02  1.57976219e+00  1.56290781e-01 -1.05868820e+00
  9.81475761e-01 -1.08742757e-01 -3.88095816e-01 -1.04996555e-01
  5.78396282e-01 -4.57158590e-01 -2.18460569e-01  5.73579863e-01
 -8.59108166e-01  1.18311822e+00 -4.16751955e-01  1.42232623e+00
  7.92952830e-01 -7.69388501e-01 -4.86694991e-01 -9.81072043e-01
  2.01593133e-01  1.11791