In [43]:
import numpy as np

In [44]:
#create array

In [45]:
a = np.array([[7,2,1],[0,3,-1],[-3,4,-2]])

In [46]:
print(a)

[[ 7  2  1]
 [ 0  3 -1]
 [-3  4 -2]]


In [47]:
#get determinate of 3x3 matrix

In [48]:
det = np.linalg.det(a)

In [49]:
print('Determinate of Matrix A:')
print(round(det))

Determinate of Matrix A:
1


In [50]:
#transpose the array

In [51]:
aneg = a.transpose()
print(aneg)

[[ 7  0 -3]
 [ 2  3  4]
 [ 1 -1 -2]]


In [52]:
detneg = np.linalg.det(a)
print('determinate of transposed Matrix A:')
print(round(detneg))

determinate of transposed Matrix A:
1


In [53]:
#gets minor of a single element in matrix

In [54]:
def minorOfElement(A,i,j):
    negA = np.delete(A,i-1,0)  
    negA = np.delete(negA,j-1,1) 
    Minor_ij = np.linalg.det(negA)   
    return np.round(Minor_ij) 

In [55]:
#loops and gets the minor of all elements in the 3x3 matrix

In [56]:
def minorMatrix(A):
    m = np.shape(A)[0]    
    minorM = np.zeros([m,m]) 
    for i in range(1,m+1):
        for j in range(1,m+1):
            minorM[i-1,j-1] = minorOfElement(A,i,j)
    return minorM

In [57]:
#element wise multiplication

In [58]:
def cofactor(A):
    m = np.shape(A)[0]  
    cofact = np.zeros([m,m])   
    for i in range(1,m+1):
        for j in range(1,m+1):
            cofact[i-1,j-1] = pow(-1,i+j)*minorOfElement(A,i,j)
    return cofact

In [59]:
print('Show minor_of_element() function working for - Matrix A:')
print(a)
print('Minor of the element at 1st row and 1st column:')
print(minorOfElement(a,1,1))

Show minor_of_element() function working for - Matrix A:
[[ 7  2  1]
 [ 0  3 -1]
 [-3  4 -2]]
Minor of the element at 1st row and 1st column:
-2.0


In [60]:
print('Matrix A:')
print(a)
print('Matrix A transposed:')
print(aneg)
print('Transposed Matrix A after minorMatrix() fuction:')
print(minorMatrix(aneg))

Matrix A:
[[ 7  2  1]
 [ 0  3 -1]
 [-3  4 -2]]
Matrix A transposed:
[[ 7  0 -3]
 [ 2  3  4]
 [ 1 -1 -2]]
Transposed Matrix A after minorMatrix() fuction:
[[ -2.  -8.  -5.]
 [ -3. -11.  -7.]
 [  9.  34.  21.]]


In [61]:
print('Transposed Matrix A after cofactor() function: ')
print(cofactor(aneg))

Transposed Matrix A cofactor() function: 
[[ -2.   8.  -5.]
 [  3. -11.   7.]
 [  9. -34.  21.]]


In [62]:
#compare output to inverse of original matrix

In [63]:
print('Matrix A inversed:')
print(np.linalg.inv(a))


Matrix A inversed:
[[ -2.   8.  -5.]
 [  3. -11.   7.]
 [  9. -34.  21.]]
